import React, { useState, useMemo } from 'react';
import { FileCode, Shield, Check, Copy, Settings } from 'lucide-react';
import { MarkdownRenderer } from './MarkdownRenderer';

interface PolicyOptions {
  disallowRoot: boolean;
  disallowPrivileged: boolean;
  requireProbes: boolean;
  requireTrustedRegistry: boolean;
}

export const PolicyWizard: React.FC = () => {
  const [engine, setEngine] = useState<'kyverno' | 'opa'>('kyverno');
  const [options, setOptions] = useState<PolicyOptions>({
    disallowRoot: true,
    disallowPrivileged: true,
    requireProbes: false,
    requireTrustedRegistry: false,
  });
  const [copied, setCopied] = useState(false);

  const toggleOption = (key: keyof PolicyOptions) => {
    setOptions(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const generatedCode = useMemo(() => {
    if (engine === 'kyverno') {
      const rules = [];
      
      if (options.disallowRoot) {
        rules.push(`
    - name: disallow-root-user
      match:
        any:
        - resources:
            kinds:
            - Pod
      validate:
        message: "Running as root is not allowed. Set securityContext.runAsNonRoot to true."
        pattern:
          spec:
            containers:
            - securityContext:
                runAsNonRoot: true`);
      }

      if (options.disallowPrivileged) {
        rules.push(`
    - name: disallow-privileged
      match:
        any:
        - resources:
            kinds:
            - Pod
      validate:
        message: "Privileged containers are not allowed."
        pattern:
          spec:
            containers:
            - securityContext:
                privileged: false`);
      }

      if (options.requireProbes) {
        rules.push(`
    - name: require-probes
      match:
        any:
        - resources:
            kinds:
            - Deployment
            - StatefulSet
            - DaemonSet
      validate:
        message: "Liveness and Readiness probes are required."
        pattern:
          spec:
            template:
              spec:
                containers:
                - livenessProbe:
                    periodSeconds: ">0"
                  readinessProbe:
                    periodSeconds: ">0"`);
      }

      if (options.requireTrustedRegistry) {
        rules.push(`
    - name: require-trusted-registry
      match:
        any:
        - resources:
            kinds:
            - Pod
      validate:
        message: "Images must come from registry.corp.com."
        pattern:
          spec:
            containers:
            - image: "registry.corp.com/*"`);
      }

      return `apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generated-security-policy
spec:
  validationFailureAction: Enforce
  background: true
  rules:${rules.length > 0 ? rules.join('') : '\n    # No rules selected'}`;
    } 
    
    else {
      // OPA Rego
      const rules = [];

      if (options.disallowRoot) {
        rules.push(`
deny[msg] {
  input.request.kind.kind == "Pod"
  container := input.request.object.spec.containers[_]
  not container.securityContext.runAsNonRoot
  msg := sprintf("Container '%v' must set runAsNonRoot to true.", [container.name])
}`);
      }

      if (options.disallowPrivileged) {
        rules.push(`
deny[msg] {
  input.request.kind.kind == "Pod"
  container := input.request.object.spec.containers[_]
  container.securityContext.privileged
  msg := sprintf("Container '%v' must not be privileged.", [container.name])
}`);
      }

      if (options.requireProbes) {
         rules.push(`
deny[msg] {
  input.request.kind.kind == "Deployment"
  container := input.request.object.spec.template.spec.containers[_]
  not container.livenessProbe
  msg := sprintf("Container '%v' is missing livenessProbe.", [container.name])
}

deny[msg] {
  input.request.kind.kind == "Deployment"
  container := input.request.object.spec.template.spec.containers[_]
  not container.readinessProbe
  msg := sprintf("Container '%v' is missing readinessProbe.", [container.name])
}`);
      }

      if (options.requireTrustedRegistry) {
        rules.push(`
deny[msg] {
  input.request.kind.kind == "Pod"
  image := input.request.object.spec.containers[_].image
  not startswith(image, "registry.corp.com/")
  msg := sprintf("Image '%v' comes from an untrusted registry.", [image])
}`);
      }

      return `package kubernetes.admission

# Generated by Policy Wizard
${rules.length > 0 ? rules.join('') : '\n# No rules selected'}`;
    }
  }, [engine, options]);

  return (
    <div className="w-full max-w-4xl mx-auto my-8 border border-gray-300 dark:border-gray-700 rounded-xl bg-white dark:bg-card-bg shadow-sm overflow-hidden animate-fade-in">
      {/* Header */}
      <div className="bg-gray-100 dark:bg-gray-800/50 p-4 border-b border-gray-200 dark:border-gray-700 flex flex-col md:flex-row justify-between items-center gap-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-purple-100 dark:bg-purple-900/30 rounded-lg text-purple-600 dark:text-purple-400">
            <Settings className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-bold text-gray-900 dark:text-white">Policy-as-Code Wizard</h3>
            <p className="text-xs text-gray-500 dark:text-gray-400">Generate security policies without writing YAML.</p>
          </div>
        </div>

        <div className="flex items-center bg-white dark:bg-gray-900 rounded-lg p-1 border border-gray-200 dark:border-gray-700">
          <button
            onClick={() => setEngine('kyverno')}
            className={`px-3 py-1.5 text-xs font-bold rounded-md transition-all ${
              engine === 'kyverno' 
                ? 'bg-blue-100 text-blue-700 dark:bg-blue-900/50 dark:text-blue-300 shadow-sm' 
                : 'text-gray-500 hover:text-gray-700 dark:text-gray-400'
            }`}
          >
            Kyverno (YAML)
          </button>
          <button
            onClick={() => setEngine('opa')}
            className={`px-3 py-1.5 text-xs font-bold rounded-md transition-all ${
              engine === 'opa' 
                ? 'bg-blue-100 text-blue-700 dark:bg-blue-900/50 dark:text-blue-300 shadow-sm' 
                : 'text-gray-500 hover:text-gray-700 dark:text-gray-400'
            }`}
          >
            OPA (Rego)
          </button>
        </div>
      </div>

      <div className="flex flex-col md:flex-row">
        {/* Controls Sidebar */}
        <div className="w-full md:w-1/3 p-6 border-r border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900/20">
          <h4 className="text-xs font-bold uppercase tracking-wider text-gray-500 mb-4">Security Controls</h4>
          <div className="space-y-3">
            <label className="flex items-start gap-3 p-3 rounded-lg hover:bg-white dark:hover:bg-gray-800 transition cursor-pointer border border-transparent hover:border-gray-200 dark:hover:border-gray-700">
              <input 
                type="checkbox" 
                checked={options.disallowRoot} 
                onChange={() => toggleOption('disallowRoot')}
                className="mt-1 w-4 h-4 text-purple-600 rounded focus:ring-purple-500"
              />
              <div>
                <span className="block text-sm font-semibold text-gray-800 dark:text-gray-200">Disallow Root User</span>
                <span className="block text-xs text-gray-500 mt-0.5">Enforces runAsNonRoot: true</span>
              </div>
            </label>

            <label className="flex items-start gap-3 p-3 rounded-lg hover:bg-white dark:hover:bg-gray-800 transition cursor-pointer border border-transparent hover:border-gray-200 dark:hover:border-gray-700">
              <input 
                type="checkbox" 
                checked={options.disallowPrivileged} 
                onChange={() => toggleOption('disallowPrivileged')}
                className="mt-1 w-4 h-4 text-purple-600 rounded focus:ring-purple-500"
              />
              <div>
                <span className="block text-sm font-semibold text-gray-800 dark:text-gray-200">Block Privileged</span>
                <span className="block text-xs text-gray-500 mt-0.5">Prevents full host access</span>
              </div>
            </label>

            <label className="flex items-start gap-3 p-3 rounded-lg hover:bg-white dark:hover:bg-gray-800 transition cursor-pointer border border-transparent hover:border-gray-200 dark:hover:border-gray-700">
              <input 
                type="checkbox" 
                checked={options.requireProbes} 
                onChange={() => toggleOption('requireProbes')}
                className="mt-1 w-4 h-4 text-purple-600 rounded focus:ring-purple-500"
              />
              <div>
                <span className="block text-sm font-semibold text-gray-800 dark:text-gray-200">Require Probes</span>
                <span className="block text-xs text-gray-500 mt-0.5">Liveness & Readiness checks</span>
              </div>
            </label>

            <label className="flex items-start gap-3 p-3 rounded-lg hover:bg-white dark:hover:bg-gray-800 transition cursor-pointer border border-transparent hover:border-gray-200 dark:hover:border-gray-700">
              <input 
                type="checkbox" 
                checked={options.requireTrustedRegistry} 
                onChange={() => toggleOption('requireTrustedRegistry')}
                className="mt-1 w-4 h-4 text-purple-600 rounded focus:ring-purple-500"
              />
              <div>
                <span className="block text-sm font-semibold text-gray-800 dark:text-gray-200">Trusted Registry</span>
                <span className="block text-xs text-gray-500 mt-0.5">Allow only registry.corp.com</span>
              </div>
            </label>
          </div>
        </div>

        {/* Code Output */}
        <div className="w-full md:w-2/3 bg-gray-900 p-0 overflow-hidden flex flex-col">
          <div className="flex justify-between items-center px-4 py-2 bg-black/40 border-b border-gray-700">
            <span className="text-xs font-mono text-gray-400">
              {engine === 'kyverno' ? 'clusterpolicy.yaml' : 'policy.rego'}
            </span>
            <button 
              onClick={handleCopy}
              className="flex items-center gap-2 text-xs text-gray-400 hover:text-white transition"
            >
              {copied ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>
          <div className="flex-1 overflow-auto p-4">
             <MarkdownRenderer content={`\`\`\`${engine === 'kyverno' ? 'yaml' : 'rego'}\n${generatedCode}\n\`\`\``} />
          </div>
        </div>
      </div>
    </div>
  );
};